- pom.xml
- src/main/java/io/jenkins/plugins/artifact_manager_s3/JCloudsBlobStore.java
As of https://github.com/jenkinsci/jenkins/pull/3302/commits/547fd6fe6ef2823d04a1517fb08f6d714ff4423a in https://github.com/jenkinsci/jenkins/pull/3302, plus matching commits in https://github.com/jenkinsci/workflow-api-plugin/pull/67, https://github.com/jenkinsci/workflow-basic-steps-plugin/pull/60, and https://github.com/jenkinsci/copyartifact-plugin/pull/100, `VirtualFile.asRemotable` has been dropped in favor of `toExternalURL` everywhere.
> asRemotable has been deleted

- src/main/java/io/jenkins/plugins/artifact_manager_s3/JCloudsArtifactManager.java
Ideally a better non-static configuration UI needed so that each run persists information about its artifact manager parameters. Otherwise reconfiguration will likely cause regressions.
https://issues.jenkins-ci.org/browse/JENKINS-50571
@reviewbybees
> [JENKINS-50571] - Make JCloudsArtifactManager fields non-final to allow configuration via System Groovy Hooks.

- src/main/java/io/jenkins/plugins/artifact_manager_s3/JCloudsArtifactManager.java
Fixes java.lang.OutOfMemoryError: Java heap space
> [JENKINS-50668] Prevent loading file in memory on upload

- src/main/java/io/jenkins/plugins/artifact_manager_s3/JCloudsApiExtensionPoint.java
- src/main/java/io/jenkins/plugins/artifact_manager_s3/JCloudsArtifactManager.java
- src/main/java/io/jenkins/plugins/artifact_manager_s3/S3BlobStore.java
for some reason it won't find it at runtime otherwise
> Need to explicitly register JClouds provider

- Jenkinsfile
Since all of the interesting tests are skipped in ci.jenkins.io anyway, there is no purpose to rerunning tests on Windows.
> Only run build on Linux

- pom.xml
- src/main/java/io/jenkins/plugins/artifact_manager_jclouds/JCloudsArtifactManager.java
- src/test/java/io/jenkins/plugins/artifact_manager_jclouds/MockBlobStore.java
- src/test/java/io/jenkins/plugins/artifact_manager_jclouds/NetworkTest.java
Working through cases of [JENKINS-50597](https://issues.jenkins-ci.org/browse/JENKINS-50597). Could be merged at any time.
> [JENKINS-50597] Network behavior tuning

- src/main/java/io/jenkins/plugins/artifact_manager_jclouds/JCloudsArtifactManager.java
- src/test/java/io/jenkins/plugins/artifact_manager_jclouds/NetworkTest.java
> [JENKINS-50597] Network behavior tuning II

- pom.xml
- src/main/java/io/jenkins/plugins/artifact_manager_jclouds/JCloudsArtifactManager.java
- src/test/java/io/jenkins/plugins/artifact_manager_jclouds/MockBlobStore.java
- src/test/java/io/jenkins/plugins/artifact_manager_jclouds/NetworkTest.java
> [JENKINS-50597] Network behavior tuning III

- src/test/java/io/jenkins/plugins/artifact_manager_s3/JCloudsVirtualFileTest.java
On CI I saw a number of test flakes like
```
arrays first differed at element [0]; expected:<[junit326418646711570612.tmp]> but was:<[xxx#?:$'"<>čॐ]>
at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:55)
at org.junit.Assert.internalArrayEquals(Assert.java:532)
at org.junit.Assert.assertArrayEquals(Assert.java:283)
at org.junit.Assert.assertArrayEquals(Assert.java:298)
at io.jenkins.plugins.artifact_manager_s3.JCloudsVirtualFileTest.listGlob(JCloudsVirtualFileTest.java:202)
```
which just seems to have been due to the test needlessly asserting a particular order.
Also there was a longstanding issue with tests listing the `S3_DIR` (rather than the per-test timestamp dir) and expecting something about the results.
> Fixing a flaky test

- pom.xml
- src/main/java/io/jenkins/plugins/artifact_manager_s3/S3BlobStore.java
- src/test/java/io/jenkins/plugins/artifact_manager_jclouds/NetworkTest.java
- src/test/java/io/jenkins/plugins/artifact_manager_s3/JCloudsVirtualFileTest.java
[JENKINS-50520](https://issues.jenkins-ci.org/browse/JENKINS-50520)
Adds a dep on https://github.com/jenkinsci/workflow-cps-plugin/pull/231.
Besides automated tests, I tried `mvn hpi:run` and also running in `java -jar jenkins.war` mode.
> [JENKINS-50520] Stop shading jclouds, update to 2.1.0, fix Guice & Guava issues

- src/main/java/io/jenkins/plugins/artifact_manager_jclouds/JCloudsArtifactManager.java
- src/main/java/io/jenkins/plugins/artifact_manager_jclouds/JCloudsVirtualFile.java
- src/test/java/io/jenkins/plugins/artifact_manager_s3/S3AbstractTest.java
#42 introduced a regression in test cleanup, because `JCloudsArtifactManager.<clinit>` creates a `RobustHTTPClient`, which from `JCloudsVirtualFileTest` barfs since it is not running in a Jenkins master JVM.
> Fix bulk blob delete

- src/main/java/io/jenkins/plugins/artifact_manager_jclouds/JCloudsArtifactManager.java
- src/main/java/io/jenkins/plugins/artifact_manager_jclouds/JCloudsVirtualFile.java
- src/test/java/io/jenkins/plugins/artifact_manager_s3/JCloudsVirtualFileTest.java
Subsumes #46 and simplifies code by allowing us to get rid of the custom `PageSetIterable` utility. Explicitly tests handling of paged responses (>1000 blobs) for the first time.
> Using BlobStores.listAll

- src/main/java/io/jenkins/plugins/artifact_manager_jclouds/JCloudsArtifactManager.java
Trying to appease https://github.com/jenkinsci/workflow-api-plugin/pull/67.
> Some Javadoc

- pom.xml
Picks up releases of https://github.com/jenkinsci/workflow-cps-plugin/pull/231, https://github.com/jenkinsci/workflow-step-api-plugin/pull/37, & https://github.com/jenkinsci/workflow-support-plugin/pull/61.
> Updating test deps to released versions

- pom.xml
- src/main/java/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStore.java
- src/main/java/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStoreConfig.java
- src/main/resources/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStoreConfig/config.jelly
- src/test/java/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStoreConfigTests.java
it is needed to have permissions to create an S3 Bucket
> Allow to create the S3 bucket from the configuration page,

- pom.xml
Otherwise 21.0 causes
`java.lang.NoSuchMethodError: com.google.common.util.concurrent.MoreExecutors.sameThreadExecutor()Lcom/google/common/util/concurrent/ListeningExecutorService;`
Broken with #62
> Lock guava to 20.0

- pom.xml
- src/main/java/io/jenkins/plugins/artifact_manager_jclouds/JCloudsArtifactManager.java
[JENKINS-52361](https://issues.jenkins-ci.org/browse/JENKINS-52361)
Downstream of https://github.com/jenkinsci/workflow-api-plugin/pull/75. With `src/main/` reverted to `master`:
```
hudson.AbortException: No such saved stash ‘empty’ found at container/test1/1/stashes/empty.tgz
at io.jenkins.plugins.artifact_manager_jclouds.JCloudsArtifactManager.unstash(JCloudsArtifactManager.java:237)
at org.jenkinsci.plugins.workflow.flow.StashManager.unstash(StashManager.java:158)
at org.jenkinsci.plugins.workflow.ArtifactManagerTest$StashFunction.apply(ArtifactManagerTest.java:269)
at org.jenkinsci.plugins.workflow.ArtifactManagerTest.wrapInContainer(ArtifactManagerTest.java:125)
at org.jenkinsci.plugins.workflow.ArtifactManagerTest.artifactStashAndDelete(ArtifactManagerTest.java:184)
at …
```
> [JENKINS-52361] Handling of empty stashes was incorrect

- pom.xml
- src/main/java/io/jenkins/plugins/artifact_manager_jclouds/JCloudsArtifactManagerFactory.java
- src/main/java/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStore.java
- src/main/java/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStoreConfig.java
- src/test/java/io/jenkins/plugins/artifact_manager_jclouds/s3/ConfigAsCodeTest.java
- src/test/resources/io/jenkins/plugins/artifact_manager_jclouds/s3/configuration-as-code.yml
[JENKINS-52304](https://issues.jenkins-ci.org/browse/JENKINS-52304)
Downstream of https://github.com/jenkinsci/aws-global-configuration-plugin/pull/4. Supersedes https://github.com/jenkinsci/configuration-as-code-plugin/pull/347, which may be closed. I expect to file a follow-up to https://github.com/jenkins-infra/evergreen/pull/139 once I get some questions answered by @batmat.
> [JENKINS-52304] Configuration-as-code support

- pom.xml
Picks up the final version of https://github.com/jenkinsci/workflow-api-plugin/pull/75. The update in #71 had to be reverted to make this plugin releasable.
> https://github.com/jenkinsci/workflow-api-plugin/pull/75 has been released

- pom.xml
- src/test/java/io/jenkins/plugins/artifact_manager_jclouds/MockApiMetadata.java
- src/test/java/io/jenkins/plugins/artifact_manager_jclouds/s3/JCloudsArtifactManagerTest.java
- src/test/java/io/jenkins/plugins/artifact_manager_jclouds/s3/JCloudsVirtualFileTest.java
Amends #9, #33, and #70 to pick up https://github.com/jclouds/jclouds/pull/1226, https://github.com/jclouds/jclouds/pull/1228, and https://github.com/jclouds/jclouds/pull/1212.
Downstream of https://github.com/jenkinsci/git-plugin/pull/616.
> jclouds 2.1.1 update

- src/main/java/io/jenkins/plugins/artifact_manager_jclouds/JCloudsVirtualFile.java
- src/test/java/io/jenkins/plugins/artifact_manager_jclouds/s3/JCloudsArtifactManagerTest.java
- src/test/java/io/jenkins/plugins/artifact_manager_jclouds/s3/JCloudsVirtualFileTest.java
Locally, with `AWS_REGION` set for tests, this test passes and I see one call to
GET https://s3.amazonaws.com/<bucketname>?location HTTP/1.1
as
```
java.lang.Exception: Stack trace
at java.lang.Thread.dumpStack(Thread.java:1336)
at io.jenkins.plugins.artifact_manager_jclouds.s3.JCloudsVirtualFileTest$1.publish(JCloudsVirtualFileTest.java:219)
at java.util.logging.Logger.log(Logger.java:738)
at java.util.logging.Logger.doLog(Logger.java:765)
at java.util.logging.Logger.log(Logger.java:788)
at java.util.logging.Logger.fine(Logger.java:1516)
at org.jclouds.logging.jdk.JDKLogger.logDebug(JDKLogger.java:51)
at org.jclouds.logging.BaseLogger.debug(BaseLogger.java:49)
at org.jclouds.rest.internal.InvokeHttpMethod.invoke(InvokeHttpMethod.java:89)
at …
```
> Suppressing live tests due to excess GetBucketLocation calls

- src/main/java/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStoreConfig.java
- src/test/java/io/jenkins/plugins/artifact_manager_jclouds/s3/JCloudsArtifactManagerTest.java
- src/test/java/io/jenkins/plugins/artifact_manager_jclouds/s3/JCloudsVirtualFileTest.java
It was determined that the multiple calls to GetBucketLocation were as a result of the role under which the CI tests were being executed not having the relevant permission. This was resulting in a 403 on the call to GetBucketLocation. This doesn't cause anything to fail from a plugin perspective but the result is not cached so the call is made repeatedly when attempting to resolve the location for each of the items in the bucket.
Having added the required permission to the CI's role, re-enabling the tests. Adding an additional check to the plugin validation that outputs a warning if a successful call to GetBucketLocation cannot be made. The warning text "GetBucketLocation failed" is added as, in the case of a lack of permissions, the error from S3 just indicates "AccessDenied", not what …
> Re-enable GetBucketLocation tests and add validation

- Jenkinsfile
- pom.xml
For Java 11 readiness, apply recommended configuration:
https://wiki.jenkins.io/display/JENKINS/Java+11+Developer+Guidelines#Java11DeveloperGuidelines-MakesureyourpluginistestedinContinuousIntegrationonJava8andJava11atthesametime
And fixing what was revealed through this.
@jenkinsci/java11-support for review.
> Java 11 readiness: Build on recommended variations (Linux only)

- pom.xml
Followup for #87 proposing an alternate fix.
This reverts commits:
* 341d5e0f3c22aca14ca9091d6b2b07339dce0095 and
* 8331f44f7f54f60fc6652983fe4bee6ee78bd610.
EXPECTED TO FAIL
> [WIP] Revert "Add the JAXB API plugin during tests when on JDK 11"

- pom.xml
Test failure surfaced during testing from 2.25 to 2.26 locally. Trying to show this in a PR, IOW in a "clean" environment.
When bumping workflow-job from 2.25 to 2.26:
```
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 24.082 s <<< FAILURE! - in io.jenkins.plugins.artifact_manager_jclouds.NetworkTest
[ERROR] repeatedRecoverableErrorUnstashing(io.jenkins.plugins.artifact_manager_jclouds.NetworkTest)  Time elapsed: 23.303 s  <<< FAILURE!
java.lang.AssertionError: 
Expected: a string containing "Retrying download"
but: was "Started
Running in Durability level: MAX_SURVIVABILITY
[Pipeline] node
Running on remote in /home/tiste/dev/github/jenkinsci/artifact-manager-s3-plugin/target/tmp/j h8761481906439906155/workspace/p
[Pipeline] {
[Pipeline] writeFile
[Pipeline] …
```
> [WIP] Update workflow-job dependency

- src/main/java/io/jenkins/plugins/artifact_manager_jclouds/JCloudsArtifactManager.java
Saw another test failure while trying to release #93.
> Another case of a missing flush after error, in this case during artifact upload

- pom.xml
Noticed thanks to https://github.com/jenkinsci/maven-hpi-plugin/pull/130. Otherwise this actually comes in via the `test` dep on `docker-fixtures`, yet is in `compile` scope.
> No need to bundle jsr305.jar

- pom.xml
- src/test/java/io/jenkins/plugins/artifact_manager_jclouds/MockApiMetadata.java
- src/test/java/io/jenkins/plugins/artifact_manager_jclouds/NetworkTest.java
- src/test/java/io/jenkins/plugins/artifact_manager_jclouds/s3/JCloudsArtifactManagerTest.java
Mainly to pick up [JCLOUDS-1447](https://jira.apache.org/jira/browse/JCLOUDS-1447) https://github.com/jclouds/jclouds/pull/1238, fixing various problems with special characters such as [JENKINS-60040](https://issues.jenkins-ci.org/browse/JENKINS-60040), but see [full release notes](https://jclouds.apache.org/releasenotes/2.2.0/).
Supersedes #99.
> [JENKINS-60040] Update to jclouds 2.2.0

- pom.xml
- src/main/java/io/jenkins/plugins/artifact_manager_jclouds/JCloudsArtifactManager.java
- src/main/java/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStore.java
- src/test/java/io/jenkins/plugins/artifact_manager_jclouds/s3/JCloudsArtifactManagerTest.java
[JENKINS-50772](https://issues.jenkins-ci.org/browse/JENKINS-50772): specify content type for uploaded files in S3, where one could be determined.
As far as determining the appropriate content for a given file, at first `java.nio.Files#probeContentType()` is called to see if that returns a non-null content type. If unsuccessful, `java.net.URLConnection#guessContentTypeFromName()` is used to pick a content type based on the file extension. For each file in the list of artifacts to be uploaded, the content type (if any) is recorded in a separate map. Additionally, the content type is passed in to the S3BlobStore method which calculates the presigned URL since the content-type header is part of the signed URL and needs to be known before generating the URL. Next, during the loop which …
> JENKINS-50772: specify content type for uploaded files in S3

- src/test/java/io/jenkins/plugins/artifact_manager_jclouds/NetworkTest.java
Even with https://github.com/jenkinsci/jenkins/pull/4422, the detail will now be elsewhere in the log record, not the `Throwable.message`.
> [JENKINS-60716] More lenient assertions about Throwable messages

- pom.xml
- src/main/java/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStoreConfig.java
At least integration tests were broken by a regression in the SDK. That is fixed in https://github.com/aws/aws-sdk-java/pull/2256, but this is probably better anyway.
> Fix for aws-java-sdk 1.11.723

- src/test/java/io/jenkins/plugins/artifact_manager_jclouds/NetworkTest.java
https://github.com/jenkinsci/workflow-job-plugin/blob/ded785da2ac68b9ecdd53dab426197fea28bd990/src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowRun.java#L618-L620 meant that
```diff
diff --git src/main/java/io/jenkins/plugins/artifact_manager_jclouds/JCloudsArtifactManager.java src/main/java/io/jenkins/plugins/artifact_manager_jclouds/JCloudsArtifactManager.java
index f6ee5e1..3c37815 100644
--- src/main/java/io/jenkins/plugins/artifact_manager_jclouds/JCloudsArtifactManager.java
+++ src/main/java/io/jenkins/plugins/artifact_manager_jclouds/JCloudsArtifactManager.java
@@ -203,6 +203,7 @@ public final class JCloudsArtifactManager extends ArtifactManager implements Sta
LOGGER.log(Level.FINE, "Ignoring blob deletion: {0}", blobPath);
return false;
}
+        Thread.sleep(1000); …
```
> Tracked down test flake

- pom.xml
[JENKINS-62776](https://issues.jenkins-ci.org/browse/JENKINS-62776): correcting regression in #122, ultimately from https://github.com/jenkinsci/maven-hpi-plugin/pull/140 or https://github.com/jenkinsci/maven-hpi-plugin/pull/172 I think. Verified via manual sanity check.
> [JENKINS-62776] Ensure WEB-INF/lib/guava-20.0.jar is bundled

- src/test/java/io/jenkins/plugins/artifact_manager_jclouds/NetworkTest.java
Yet more flakes, this time from https://github.com/jenkinsci/jenkins/pull/4368 in 2.221+. (Distinct from #116 & #134.)
> Flakes in NetworkTest.errorCleaningArtifacts due to BackgroundGlobalBuildDiscarder

- pom.xml
- src/main/java/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStoreConfig.java
- src/test/java/io/jenkins/plugins/artifact_manager_jclouds/s3/MinioIntegrationTest.java
Uses https://github.com/jenkinsci/jenkins-test-harness/pull/280.
If I deliberately break stuff
```diff
diff --git pom.xml pom.xml
index 3a9eb40..05d6355 100644
--- pom.xml
+++ pom.xml
@@ -271,20 +271,6 @@
</dependencies>
</dependencyManagement>
-  <build>
-      <plugins>
-          <plugin>
-            <groupId>org.jenkins-ci.tools</groupId>
-            <artifactId>maven-hpi-plugin</artifactId>
-            <configuration>
-              
-              <maskClasses>com.google.common.</maskClasses>
-            </configuration>
-          </plugin>
-
-      </plugins>
-  </build>
-
<repositories>
<repository>
<id>repo.jenkins-ci.org</id>
```
then I get the error I expect:
```
org.jvnet.hudson.test.RealJenkinsRule$ProxyException: 
java.lang.AssertionError: unexpected build status; build …
```
> [JENKINS-41827] Running MinioIntegrationTest in a more realistic context

- pom.xml
- src/test/java/io/jenkins/plugins/artifact_manager_jclouds/s3/MinioIntegrationTest.java
Picking up https://github.com/jenkinsci/jenkins-test-harness/pull/287 since I have seen `MinioIntegrationTest` be flaky in CI, perhaps due to JVM ergonomics issues. Also have an unreproduced report of a flaky error on Java 11
```
…	WARNING	j.u.ErrorLoggingScheduledThreadPoolExecutor#afterExecute: failure in task not wrapped in SafeTimerTask
groovy.lang.MissingMethodException: No signature of method: RealJenkinsRuleInit.invokeLater() is applicable for argument types: () values: []
at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:58)
at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:81)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
at …
```
> RealJenkinsRule updated, passing -Xmx100m

- src/main/java/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStoreConfig.java
…with assertions enabled anyway. Also allows the stack trace to be displayed; otherwise just showed **AssertionError:Unknown error** which was not too helpful. Amends #55.
> doValidateS3BucketConfig could throw AssertionError

- pom.xml
- src/test/java/io/jenkins/plugins/artifact_manager_jclouds/NetworkTest.java
- src/test/java/io/jenkins/plugins/artifact_manager_jclouds/s3/JCloudsArtifactManagerTest.java
[JENKINS-66984](https://issues.jenkins.io/browse/JENKINS-66984)
Downstream of https://github.com/jenkinsci/jenkins/pull/5707.
#215 and #226 might need to wait for a Guice upgrade.
See e.g. #140 for motivation.
> [JENKINS-66984] Pick up newer Guava from core

- pom.xml
- src/test/java/io/jenkins/plugins/artifact_manager_jclouds/MockApiMetadata.java
Derived from #189. Follows up #244 to pick up https://github.com/jenkinsci/jenkins/pull/5858. https://github.com/jenkinsci/artifact-manager-s3-plugin/pull/226#issuecomment-972041078 tracks a further jclouds upgrade. Possibly solves [JENKINS-65824](https://issues.jenkins.io/browse/JENKINS-65824).
> Update jclouds, picking up Guice from core

- pom.xml
Continuing #215. Contra https://github.com/jenkinsci/artifact-manager-s3-plugin/pull/226#issuecomment-972041078 it seems that we can do this now?
```
Bundling transitive dependency jaxb-impl-2.3.3.jar (via aws-s3)
Bundling transitive dependency jakarta.xml.bind-api-2.3.3.jar (via aws-s3)
Bundling transitive dependency javax.ws.rs-api-2.0.1.jar (via aws-s3)
```
:shrug:
> Update jclouds to 2.4.0

- pom.xml
Demonstrating that with the inclusion of `guice-bom` in jenkinsci/jenkins#6014 that plugins no longer need to declare an explicit version of Guice artifacts.
> Use `guice-bom` from 2.324

- pom.xml
- src/main/java/io/jenkins/plugins/artifact_manager_jclouds/JCloudsArtifactManager.java
- src/main/java/io/jenkins/plugins/artifact_manager_jclouds/TikaUtil.java
- src/test/java/io/jenkins/plugins/artifact_manager_jclouds/s3/JCloudsArtifactManagerTest.java
Use tika to detect content type more accurately.
I perform a manual test that the content type in s3 is expected.
> Feat: Use tika to detect content type more accurately

- pom.xml
- src/main/java/io/jenkins/plugins/artifact_manager_jclouds/JCloudsVirtualFile.java
- src/main/java/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStoreConfig.java
- src/test/java/io/jenkins/plugins/artifact_manager_jclouds/MockBlobStore.java
- src/test/java/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStoreConfigTest.java
Hello folks :wave:
I'm currently following the [Improve a Plugin documentation](https://www.jenkins.io/doc/developer/tutorial-improve/) for
Jenkins plugins modernization, and noticed we could [add more Spotbugs checks](https://www.jenkins.io/doc/developer/tutorial-improve/add-more-spotbugs-checks/) in this plugin.
So here's a PR following the documentation recommendation by increasing the Spotbugs checks, as well as fixing the
reported issues.
Let me know if that sounds interesting to you or if any other modifications are needed.
Thanks a lot!
> Increasing Spotbugs level and fixing Spotbugs issues

- src/test/java/io/jenkins/plugins/artifact_manager_jclouds/s3/S3AbstractTest.java
At some point apparently `AWSCredentialsProvider.getCredentials` stopped returning `null` and started returning an `AnonymousAWSCredentials` object, causing tests to fail later in `CredentialsAwsGlobalConfiguration.sessionCredentialsFromInstanceProfile`.
> Skip test if using `AnonymousAWSCredentials`

- pom.xml
- src/main/java/io/jenkins/plugins/artifact_manager_jclouds/JCloudsArtifactManager.java
- src/test/java/io/jenkins/plugins/artifact_manager_jclouds/s3/JCloudsArtifactManagerTest.java
I noticed a case where artifacts were not being stored for a build when using `withMaven` and `JCloudsArtifactManager`. There seem to be two related problems, and fixing either one of them should fix the issue.
I currently do not have AWS access and so am not able to test this PR, which is why it is a draft.
1. Content type detection currently uses the keys of `Map<String, String> artifacts` in `ArtifactManager.archive` when looking for the files in the workspace, however based on the [Javadoc](https://github.com/jenkinsci/jenkins/blob/5755957b3ab2f2826edea20660b2a82f7537f456/core/src/main/java/jenkins/model/ArtifactManager.java#L63) the keys are actually the archive paths and the workspace paths are the values. This does not matter for …
> `JCloudsArtifactManager` fails to archive artifacts when their workspace path is not identical to their archive path

- src/main/java/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStore.java
“Test 2” in [JENKINS-71078](https://issues.jenkins.io/browse/JENKINS-71078) looks like a misconfiguration: `disableSessionToken` means you must specify static credentials.
> [JENKINS-71078] Better report lack of AWS credentials

- src/test/java/io/jenkins/plugins/artifact_manager_jclouds/s3/MinioIntegrationTest.java
Complementing https://github.com/jenkins-infra/pipeline-library/pull/658. Not touching https://github.com/jenkinsci/artifact-manager-s3-plugin/blob/12f03e8929826c17f76c885661c792265f6d824c/Jenkinsfile#L1-L4 unless I am told it is wrong/deprecated (and what the replacement should be).
https://github.com/jenkins-infra/helpdesk/issues/3548 not particularly relevant in this context—I am fine with the test running only on Linux.
> `MinioIntegrationTest` should assume Docker Linux specifically

- src/test/java/io/jenkins/plugins/artifact_manager_jclouds/NetworkTest.java
https://github.com/jenkinsci/workflow-job-plugin/pull/357#discussion_r1204538812 would break an assertion because the message is now sent to the build rather than system log (which we want).
> Adapt to workflow-job-plugin#357

- pom.xml
See https://issues.jenkins.io/browse/JENKINS-72441
jcloud bundle an old version of gson. Fixed on 2.6.0 but unreleased
Automated tests
```[tasklist]
```
> JENKINS-72441 Hide parent gson classes

- src/test/java/io/jenkins/plugins/artifact_manager_jclouds/MockBlobStore.java
- Current use of URL builder does not cover IPv6
- If we run a test using this code on an IPv6 environment we will get the following exception
```
java.net.MalformedURLException: Error at index 0 in: "::37351"
at java.base/java.net.URL.<init>(URL.java:679)
at java.base/java.net.URL.<init>(URL.java:541)
at java.base/java.net.URL.<init>(URL.java:488)
at io.jenkins.plugins.artifact_manager_jclouds.MockBlobStore.getContext(MockBlobStore.java:144)
at io.jenkins.plugins.artifact_manager_jclouds.NetworkTest.configureManager(NetworkTest.java:88)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.jvnet.hudson.test.JenkinsRule$1.evaluate(JenkinsRule.java:656)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.lang.Thread.run(Thread.java:829) …
```
> Adapt to test on IPv6

- .mvn/extensions.xml
- pom.xml
And use bom version when possible
https://github.com/jenkinsci/artifact-manager-s3-plugin/pull/446
https://github.com/jenkinsci/artifact-manager-s3-plugin/pull/445
https://github.com/jenkinsci/artifact-manager-s3-plugin/pull/444
https://github.com/jenkinsci/artifact-manager-s3-plugin/pull/436
https://github.com/jenkinsci/artifact-manager-s3-plugin/pull/435
https://github.com/jenkinsci/artifact-manager-s3-plugin/pull/428
https://github.com/jenkinsci/artifact-manager-s3-plugin/pull/420
https://github.com/jenkinsci/artifact-manager-s3-plugin/pull/418
https://github.com/jenkinsci/artifact-manager-s3-plugin/pull/403
Automated tests
```[tasklist]
```
> Bump to Jenkins core 2.401 and refresh dependencies

- pom.xml
- src/main/java/io/jenkins/plugins/artifact_manager_jclouds/JCloudsVirtualFile.java
- src/main/java/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStore.java
Supersedes #452, #453, #454, #455.
> POM updates

- README.md
- src/main/java/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStoreConfig.java
- src/main/resources/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStoreConfig/config.jelly
While opening https://github.com/jenkinsci/jobcacher-plugin/issues/262 and wanted to implement  https://github.com/jenkinsci/jobcacher-plugin/issues/256 I found the title confusing and too generic.
It makes think that the configuration can be used for other plugin but it's only for Artifact Storage management.
Other plugin like `jobcacher` that upload caches to S3 endpoint have their own configuration and can benefit only (if they want to) of credentials from `aws-global-configuration-plugin`
```[tasklist]
```
> Rename configuration title to be more specific

- pom.xml
Backports just enough of #450 to allow 2.440.x-based PCT to pass after https://github.com/jenkinsci/trilead-api-plugin/pull/131. #447 solved the issue for `RealJenkinsRule` but not `JenkinsRule`.
> Exclude GSON from test classpath

- src/test/java/io/jenkins/plugins/artifact_manager_jclouds/NetworkTest.java
See [https://issues.jenkins.io/browse/JENKINS-73835](https://issues.jenkins.io/browse/JENKINS-73835) and https://github.com/jenkinsci/jenkins/pull/9810. That PR changes which logger reports the log rotation error, causing `NetworkTest.errorCleaningArtifacts` to fail consistently against Jenkins 2.481+.
I bumped the parent POM to 5.1 and Jenkins version to 2.481 and verified that the test failed consistently without this patch, and passed consistently with it.
> [JENKINS-73835] Adjust `NetworkTest.errorCleaningArtifacts` test to record more loggers for compatibility with newer cores

- src/main/java/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStoreConfig.java
- src/test/java/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStoreConfigFipsEnabledTest.java
- src/test/java/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStoreConfigTest.java
- src/test/java/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStoreConfigTestFipsEnabled.java
This PR is to fix non FIPS compliant TLS usage in **artifact-manager-s3** , this is done by ensuring that **useHttp flag** is not allowed to be true while operating in **FIPS mode**.
- Automated Unit Testing:
Added a dedicated unit test **S3BlobStoreConfigTestFipsEnabled** to validate that setting the **useHttp flag** to true while in FIPS mode results in an Error , ensuring compliance.
- Manual Testing:
Did Manual testing to verify my changes to ensure that everything is working properly.
**On clicking use insecure Http**
**On clicking validate button further**
**On clicking Save**
=======================================================
**Link to issue ->** [https://cloudbees.atlassian.net/browse/BEE-52993](https://cloudbees.atlassian.net/browse/BEE-52993)
> Added validation for useHttp flag to fix the non FIPS compliant TLS usage.

- pom.xml
- src/test/java/io/jenkins/plugins/artifact_manager_jclouds/MockApiMetadata.java
Reverting #447, since 2.6.0 contains the fix for [JCLOUDS-1620](https://issues.apache.org/jira/browse/JCLOUDS-1620).
jclouds 2.6.0 requires Guice 7.0.0, which is above the version delivered by core (6.0.0), but so far I have found no issue ignoring the upper bounds error and continuing to deliver Guice 6.0.0. Guice 6.0.0 supports both `javax` and `jakarta` imports, while 7.0.0 drops support for `javax`, so 6.0.0 makes more sense for Jenkins. Unfortunately this required adding a few temporary workarounds to the POM file.
`mvn clean verify`, including `MinioIntegrationTest`
I would appreciate if someone could do a manual test run with an AWS account, since I believe CI unfortunately is not enough.
> Upgrade jclouds from 2.5.0 to 2.6.0

- src/test/java/io/jenkins/plugins/artifact_manager_jclouds/s3/JCloudsVirtualFileTest.java
Checking for regression from #567, I ran `mvn clean verify` locally after `aws sso login` and got a 403 failure in this test enabled since #78. I guess I must have forgotten to try a full build in #351, and in CI the SSO code is unused.
> Fixing `JCloudsVirtualFileTest.testAmpersand` for SSO

- .github/dependabot.yml
- .github/release-drafter.yml
https://github.com/jenkinsci/artifact-manager-s3-plugin/pull/620#issuecomment-2871419035 and also `release-drafter.yml` is unnecessary
> Simplifying `.github`

- src/main/java/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStore.java
It looks signer really a region
Previous have been with some env var including a region such `AWS_REGION=my-region-is-the-best` so it was auto detected
> Get region from global configuration for signing

- src/main/java/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStore.java
- src/main/java/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStoreConfig.java
- src/test/java/io/jenkins/plugins/artifact_manager_jclouds/s3/JCloudsVirtualFileTest.java
Using ec-2 with instance profile credentials. 
Having this stacktrace 
```
software.amazon.awssdk.core.exception.SdkClientException: Unable to load region from any of the providers in the chain software.amazon.awssdk.regions.providers.DefaultAwsRegionProviderChain@a16c0c8: [software.amazon.awssdk.regions.providers.SystemSettingsRegionProvider@3a65b6b2: Unable to load region from system settings. Region must be specified either via environment variable (AWS_REGION) or  system property (aws.region)., software.amazon.awssdk.regions.providers.AwsProfileRegionProvider@10fa4669: No region provided in profile: default, software.amazon.awssdk.regions.providers.InstanceProfileRegionProvider@2eeef836: Unable to contact EC2 metadata service.]
at PluginClassLoader for …
```
> Enforce region for aws sdk calls

- .mvn/extensions.xml
- pom.xml
- src/test/java/io/jenkins/plugins/artifact_manager_jclouds/MockBlobStoreTest.java
- src/test/java/io/jenkins/plugins/artifact_manager_jclouds/s3/AbstractIntegrationTest.java
- src/test/java/io/jenkins/plugins/artifact_manager_jclouds/s3/JCloudsArtifactManagerTest.java
#648 extended with https://github.com/jenkinsci/ssh-agents-plugin/pull/607 / https://github.com/jenkinsci/workflow-api-plugin/pull/416.
> Update dependencies, use `OutboundAgent` for tests

- src/main/java/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStore.java
- src/main/java/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStoreConfig.java
For example when the plugin is configured as code and `prefix` is simply omitted. Otherwise can get `"null"` prepended to start of blob paths.
> Tolerate null `S3BlobStoreConfig.prefix`
