pom.xml

Instead of library directly
Retake of #1

Use aws sdk plugin

---

src/main/java/io/jenkins/plugins/artifact_manager_s3/JCloudsApiExtensionPoint.java
src/main/java/io/jenkins/plugins/artifact_manager_s3/JCloudsArtifactManager.java
src/main/java/io/jenkins/plugins/artifact_manager_s3/JCloudsBlobStore.java
src/main/java/io/jenkins/plugins/artifact_manager_s3/S3BlobStore.java
src/test/java/io/jenkins/plugins/artifact_manager_s3/JCloudsArtifactManagerTest.java
src/test/java/io/jenkins/plugins/artifact_manager_s3/JCloudsBlobStoreTest.java

Using presigned URLs
[JENKINS-50518](https://issues.jenkins-ci.org/browse/JENKINS-50518)

[JENKINS-50518] Only run upload/download in the agent

---

src/test/java/io/jenkins/plugins/artifact_manager_s3/JCloudsBlobStoreTest.java

Showing that jclouds can not handle s3 keys with ampersand '&'

Add tests for weird characters

---

pom.xml
src/test/java/io/jenkins/plugins/artifact_manager_s3/JCloudsAbstractTest.java
src/test/java/io/jenkins/plugins/artifact_manager_s3/JCloudsArtifactManagerTest.java

Follows up #4, picking up https://github.com/jenkinsci/workflow-api-plugin/pull/67/commits/915f652453f8199069459ad733193e30492d96e6 and https://github.com/jenkinsci/docker-fixtures/pull/19 to verify that upload and download operations really work inside a clean environment.

[JENKINS-50518] Run tests inside Dockerized agents

---

src/main/java/io/jenkins/plugins/artifact_manager_s3/JCloudsArtifactManager.java
src/test/java/io/jenkins/plugins/artifact_manager_s3/JCloudsAbstractTest.java
src/test/java/io/jenkins/plugins/artifact_manager_s3/JCloudsArtifactManagerTest.java
src/test/java/io/jenkins/plugins/artifact_manager_s3/JCloudsBlobStoreTest.java

Delete all test files after each test

---

pom.xml

jenkins.version=2.118

---

.mvn/extensions.xml

https://issues.jenkins-ci.org/browse/JENKINS-51187

[JENKINS-51187] Moving git-changelist-maven-extension into incrementals-tools

---

.gitignore
.mvn/extensions.xml
pom.xml

Picks up https://github.com/jenkinsci/plugin-pom/pull/105.

[JENKINS-51247] Simplified use of flatten-maven-plugin

---

pom.xml
src/main/java/io/jenkins/plugins/artifact_manager_s3/JCloudsArtifactManager.java
src/main/java/io/jenkins/plugins/artifact_manager_s3/S3BlobStore.java
src/test/java/io/jenkins/plugins/artifact_manager_s3/JCloudsArtifactManagerTest.java

[JENKINS-51390](https://issues.jenkins-ci.org/browse/JENKINS-51390)
https://github.com/jenkinsci/workflow-support-plugin/pull/61 is the workaround; the real fix is in https://github.com/jclouds/jclouds/pull/1211.

java.io.NotSerializableException from AWSResponseException

---

src/main/java/io/jenkins/plugins/artifact_manager_s3/JCloudsArtifactManager.java

Wrap RuntimeException in IOException

---

pom.xml
src/main/java/io/jenkins/plugins/artifact_manager_jclouds/BlobStoreProvider.java
src/main/java/io/jenkins/plugins/artifact_manager_jclouds/JCloudsArtifactManager.java
src/main/java/io/jenkins/plugins/artifact_manager_s3/S3BlobStore.java
src/test/java/io/jenkins/plugins/artifact_manager_jclouds/MockBlobStore.java
src/test/java/io/jenkins/plugins/artifact_manager_jclouds/MockBlobStoreTest.java
src/test/java/io/jenkins/plugins/artifact_manager_s3/JCloudsArtifactManagerTest.java

[JENKINS-51523](https://issues.jenkins-ci.org/browse/JENKINS-51523)
Subsumes and fixes #31.

[JENKINS-51523] Delegate artifact lifecycle management to S3 (redux)

---

pom.xml
src/test/java/io/jenkins/plugins/artifact_manager_jclouds/NetworkTest.java

Picks up https://github.com/jenkinsci/apache-httpcomponents-client-4-api-plugin/commit/5d1d316e683843efbee460980b9e2c286e76bbd2 from https://github.com/jenkinsci/apache-httpcomponents-client-4-api-plugin/pull/9.

Matching change

---

src/main/java/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStoreConfig.java
src/test/java/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStoreConfigTests.java

* Throw an exception with wrong configuration values
* some tests
previous PR https://github.com/jenkinsci/artifact-manager-s3-plugin/pull/52

throw exception on wrong configuration, some test about form validations 

---

pom.xml

Thanks to release from @dwnusbaum.

apache-httpcomponents-client-4-api 4.5.5-3.0

---

src/main/java/io/jenkins/plugins/artifact_manager_jclouds/JCloudsVirtualFile.java

When there are no permissions to write or delete in S3

[JENKINS-51963] Do not show stack traces on authorization errors

---

src/main/java/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStoreConfig.java

[JENKINS-52250](https://issues.jenkins-ci.org/browse/JENKINS-52250)
* replace the constant that list the Regions

[JENKINS-52250] list all default regions

---

src/main/java/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStoreConfig.java

[JENKINS-52254](https://issues.jenkins-ci.org/browse/JENKINS-52254)

[JENKINS-52254]use the prefix on config validation

---

src/main/java/io/jenkins/plugins/artifact_manager_jclouds/JCloudsArtifactManager.java

protect against NPE

---

pom.xml
src/test/java/io/jenkins/plugins/artifact_manager_jclouds/s3/JCloudsArtifactManagerTest.java

See [JENKINS-52151](https://issues.jenkins-ci.org/browse/JENKINS-52151). Passes when you build https://github.com/jclouds/jclouds/pull/1226 and
```diff
diff --git a/pom.xml b/pom.xml
index db1067d..2fe13c8 100644
--- a/pom.xml
+++ b/pom.xml
@@ -16,7 +16,7 @@
<properties>
<revision>1.1</revision>
<changelist>-SNAPSHOT</changelist>
-    <jclouds.version>2.1.0</jclouds.version>
+    <jclouds.version>2.2.0-SNAPSHOT</jclouds.version>
<jenkins.version>2.121.1</jenkins.version>
<java.level>8</java.level>
<workflow-api-plugin.version>2.28</workflow-api-plugin.version>
diff --git a/src/test/java/io/jenkins/plugins/artifact_manager_jclouds/s3/JCloudsArtifactManagerTest.java b/src/test/java/io/jenkins/plugins/artifact_manager_jclouds/s3/JCloudsArtifactManagerTest.java
index cf4d476..07aca1a 100644 …
```

[JENKINS-52151] Reproduced problem in test

---

pom.xml
src/test/java/io/jenkins/plugins/artifact_manager_jclouds/s3/JCloudsArtifactManagerTest.java

Downstream of https://github.com/jenkinsci/aws-global-configuration-plugin/pull/8.

 [JENKINS-56004] Integration test for (lack of) permission check

---

Jenkinsfile
pom.xml

JAXB fix to make plugin work on Java 11

---

src/main/java/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStore.java
src/test/java/io/jenkins/plugins/artifact_manager_jclouds/s3/JCloudsVirtualFileTest.java

[JENKINS-59493] Use S3 client to get public URI (follow-up)

---

src/main/java/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStore.java

[JENKINS-59493](https://issues.jenkins-ci.org/browse/JENKINS-59493)
Use the S3 client to get public S3 URIs. This ensures that the right URI is generated always (for example, the region is includes and for other partitions, such as China, the correct domain is used).

[JENKINS-59493] Use S3 client to get public URI

---

src/main/java/io/jenkins/plugins/artifact_manager_jclouds/JCloudsArtifactManager.java
src/main/java/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStore.java
src/test/java/io/jenkins/plugins/artifact_manager_jclouds/s3/JCloudsArtifactManagerTest.java

Amends #100 by @robinverduijn.

JENKINS-50772: specify content type for uploaded files in S3 (follow-ups)

---

Jenkinsfile

External systems can write their own scripts.

Just use buildPlugin

---

pom.xml

commons-codec should be picked up from jenkins-core

---

Jenkinsfile

Cannot use ACI agents since some tests rely on Docker fixtures.

---

pom.xml

Remove explicit versions managed by BOM

---

.github/dependabot.yml
pom.xml

Upgrade guava to 30.0-jre
Pending `workflow-support` release and manual testing.

Upgrade Guava to latest release

---

Jenkinsfile

enable jdk11 windows builds

---

pom.xml

As noted in https://github.com/jenkinsci/artifact-manager-s3-plugin/pull/238#discussion_r722265634

This entry makes no sense in depmgmt

---

README.md
src/main/java/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStoreConfig.java
src/main/resources/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStoreConfig/config.jelly
src/main/resources/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStoreConfig/help-useTransferAcceleration.html

As per description; adds support for using s3 transfer acceleration . It can also create buckets with this feature enabled.

[JENKINS-52888] Add option to use S3 transfer acceleration

---

src/test/java/io/jenkins/plugins/artifact_manager_jclouds/s3/JCloudsVirtualFileTest.java

Seeing frequent test flakes
```
org.jclouds.http.HttpResponseException: Server rejected operation connecting to PUT https://…bucket.s3.amazonaws.com/…/junit….tmp HTTP/1.1
at org.jclouds.http.internal.BaseHttpCommandExecutorService.invoke(BaseHttpCommandExecutorService.java:120)
at org.jclouds.rest.internal.InvokeHttpMethod.invoke(InvokeHttpMethod.java:91)
at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:74)
at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:45)
at org.jclouds.rest.internal.DelegatesToInvocationFunction.handle(DelegatesToInvocationFunction.java:156)
at org.jclouds.rest.internal.DelegatesToInvocationFunction.invoke(DelegatesToInvocationFunction.java:123)
at com.sun.proxy.$Proxy152.putObject(Unknown Source)
at …
```

`BlobStore.putBlob` sometimes fails

---

pom.xml

Use the latest release
Fix #309

[chore] Upgrade tika to 2.4.1

---

README.md

The properties was moved to aws global configuration but the documentation was not updated as it should
Signed-off-by: Michael Trimarchi <michael@amarulasolutions.com>

Fix documentation of `sessionDuration`

---

.github/CODEOWNERS
.mvn/extensions.xml
pom.xml
src/test/java/io/jenkins/plugins/artifact_manager_jclouds/s3/JCloudsArtifactManagerTest.java

Refresh deps

---

src/main/java/io/jenkins/plugins/artifact_manager_jclouds/BlobStoreProvider.java
src/main/java/io/jenkins/plugins/artifact_manager_jclouds/JCloudsArtifactManager.java
src/main/java/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStore.java
src/main/java/io/jenkins/plugins/artifact_manager_jclouds/s3/S3BlobStoreConfig.java

Signed-off-by: Olivier Lamy <olamy@apache.org>

reuse same s3client and presigner when archiving multiple files

---

.mvn/extensions.xml
pom.xml
src/test/java/io/jenkins/plugins/artifact_manager_jclouds/MockBlobStoreTest.java
src/test/java/io/jenkins/plugins/artifact_manager_jclouds/s3/AbstractIntegrationTest.java
src/test/java/io/jenkins/plugins/artifact_manager_jclouds/s3/JCloudsArtifactManagerTest.java

Draft, as https://github.com/jenkinsci/workflow-api-plugin/pull/414 is required to replace `docker-fixtures` (see https://github.com/jenkinsci/docker-fixtures/pull/122#issuecomment-3046351724)
* Bump baseline and dependencies
* Remove docker-fixtures
`mvn clean verify`

Require Jenkins 2.504.1
